// // import type { Metadata } from "next";
// // import localFont from "next/font/local";
// // import "./globals.css";

// // const geistSans = localFont({
// //   src: "./fonts/GeistVF.woff",
// //   variable: "--font-geist-sans",
// //   weight: "100 900",
// // });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }
// // app/layout.js
// // app/layout.js
// // app/layout.js

// import { ReactNode } from 'react';
// import './globals.css'; 

// interface LayoutProps {
//   children: ReactNode;
// }

// export default function Layout({ children }: LayoutProps) {
//   return (
//     <html lang="en">
//       <head>
//         <meta charSet="UTF-8" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <title>My Next.js App</title>
//         <link rel="icon" href="/favicon.ico" />
//       </head>
//       <body className="bg-gray-100 font-sans text-gray-900">
//         <header className="bg-blue-600 text-white p-4">
//           <nav className="container mx-auto">
//             <ul className="flex space-x-4">
//               <li>
//                 <a href="/" className="hover:underline">Home</a>
//               </li>
//               <li>
//                 <a href="/about" className="hover:underline">About</a>
//               </li>
//               <li>
//                 <a href="/admin" className="hover:underline">Admin</a>
//               </li>
//             </ul>
//           </nav>
//         </header>

//         <main className="container mx-auto p-4">{children}</main>

//         <footer className="bg-blue-600 text-white text-center p-4 mt-8">
//           <p>&copy; 2024 My Next.js App</p>
//         </footer>
//       </body>
//     </html>
//   );
// }

// import React, { ReactNode } from 'react';
// import Link from 'next/link';
// import { FaHome, FaInfoCircle, FaRegFolder, FaQuestionCircle, FaUserPlus, FaPhone } from 'react-icons/fa';

// import './globals.css';

// interface LayoutProps {
//   children: ReactNode;
// }

// export default function Layout({ children }: LayoutProps) {
//   return (
//     // תגית <html> ו-<body> נוספות כאן
//     <html lang="he">
//       <body className="bg-gray-50">
//         <div className="flex flex-col min-h-screen">
//           {/* כותרת עליונה */}
//           <header className="bg-blue-600 text-white py-4 shadow-md">
//             <nav className="container mx-auto flex justify-between items-center px-6">
//               {/* <Link href="/home" className="text-2xl font-bold">
//                 Ting Global Academy
//               </Link> */}
//               <Link href="/home">
//                 <img src="/images/logo.png" alt="Ting Global Academy" className="h-8 sm:h-12" />

//               </Link>
//               <div className="space-x-6">
//                 {/* <Link href="/home" className="hover:text-gray-300">
//                   home
//                 </Link>  */}
//                 <Link href="/home" className="flex items-center hover:text-gray-300">
//                   <FaHome className="mr-2" />
//                   Home
//                 </Link>
//                 <Link href="/about" className="flex items-center hover:text-gray-300">
//                   <FaInfoCircle className="mr-2" />
//                   About Us
//                 </Link>
//                 {/* <Link href="/about" className="hover:text-gray-300">
//                   About Us
//                 </Link> */}
//                 {/* <Link href="/program" className="hover:text-gray-300">
//                   Program
//                 </Link> */}
//                 <Link href="/program" className="flex items-center hover:text-gray-300">
//                   <FaRegFolder className="mr-2" />
//                   Program
//                 </Link>
//                 {/* <Link href="/FAQ" className="hover:text-gray-300">
//                   FAQ
//                 </Link> */}
//                 <Link href="/FAQ" className="flex items-center hover:text-gray-300">
//                   <FaQuestionCircle className="mr-2" />                   FAQ
//                 </Link>
//                 {/* <Link href="/join" className="hover:text-gray-300">
//                   Join
//                 </Link> */}
//                 <Link href="/join" className="flex items-center hover:text-gray-300">
//                   <FaUserPlus className="mr-2" />
//                   Join
//                 </Link>
//                 {/* <Link href="/contact" className="hover:text-gray-300">Contact</Link> */}
//                 <Link href="/contact" className="flex items-center hover:text-gray-300">
//                   <FaPhone className="mr-2" />
//                   Contact
//                 </Link>
//               </div>
//               {/* כפתור המבורגר למכשירים קטנים */}
//               <div className="md:hidden">
//                 <button className="text-white" aria-label="Open menu">
//                   <div className="w-8 h-1 bg-white mb-2"></div>
//                   <div className="w-8 h-1 bg-white mb-2"></div>
//                   <div className="w-8 h-1 bg-white"></div>
//                 </button>
//               </div>

//             </nav>
//           </header>

//           {/* תוכן הדף */}
//           <main className="container mx-auto flex-1 p-6">
//             {children}
//           </main>

//           {/* כותרת תחתונה */}
//           <footer className="bg-blue-600 text-white py-4">
//             <div className="container mx-auto text-center">
//               © 2025 Ting Global Academy . All rights reserved.
//             </div>
//           </footer>
//         </div>
//       </body>
//     </html>
//   );
// }
'use client';

import React, { ReactNode, useState } from 'react';
import Link from 'next/link';
import { FaHome, FaInfoCircle, FaRegFolder, FaQuestionCircle, FaUserPlus, FaPhone, FaUniversity } from 'react-icons/fa';

import './globals.css';

interface LayoutProps {
  children: ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  // State למעקב אחרי מצב התפריט (פתוח או סגור)
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  // פונקציה להפעלת/סגירת התפריט
  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    // הוספת תגית <html> ו-<body>
    <html lang="he">
      <body className="bg-gray-50">
        <div className="flex flex-col min-h-screen">
          {/* כותרת עליונה */}
          <header className="bg-blue-600 text-white py-4 shadow-md">
            <nav className="container mx-auto flex justify-between items-center px-6">
              {/* הלוגו בצד שמאל */}
              <Link href="/home">
                <img src="/images/logo.png" alt="Ting Global Academy" className="h-8 sm:h-20" />
              </Link>

              {/* תפריט ניווט */}
              <div className="hidden md:flex space-x-6">
                <Link href="/home" className="flex items-center hover:text-gray-300">
                  <FaHome className="mr-2" />
                  Home
                </Link>
                <Link href="/about" className="flex items-center hover:text-gray-300">
                  <FaInfoCircle className="mr-2" />
                  About Us
                </Link>
                <Link href="/program" className="flex items-center hover:text-gray-300">
                  <FaRegFolder className="mr-2" />
                  Program
                </Link>
                <Link href="/FAQ" className="flex items-center hover:text-gray-300">
                  <FaQuestionCircle className="mr-2" />
                  FAQ
                </Link>
                {/* <Link href="/scholarships" className="flex items-center hover:text-gray-300">
                  <FaUniversity className="mr-2" />
                  Scholarships & Financial Aid
                </Link> */}
                
                <Link href="/join" className="flex items-center hover:text-gray-300">
                  <FaUserPlus className="mr-2" />
                  Join
                </Link>
                <Link href="/contact" className="flex items-center hover:text-gray-300">
                  <FaPhone className="mr-2" />
                  Contact
                </Link>
              </div>

              {/* כפתור המבורגר למכשירים קטנים */}
              <div className="md:hidden">
                <button
                  className="text-white"
                  aria-label="Open menu"
                  onClick={toggleMenu} // קריאה לפונקציה לפתיחת/סגירת התפריט
                >
                  <div className="w-8 h-1 bg-white mb-2"></div>
                  <div className="w-8 h-1 bg-white mb-2"></div>
                  <div className="w-8 h-1 bg-white"></div>
                </button>
              </div>
            </nav>
          </header>

          {/* תפריט המבורגר שנראה רק כאשר הוא פתוח */}
          {isMenuOpen && (
            <div className="md:hidden bg-blue-600 text-white py-4">
              <div className="flex flex-col space-y-4 items-center">
                <Link href="/home" className="flex items-center hover:text-gray-300">
                  <FaHome className="mr-2" />
                  Home
                </Link>
                <Link href="/about" className="flex items-center hover:text-gray-300">
                  <FaInfoCircle className="mr-2" />
                  About Us
                </Link>
                <Link href="/program" className="flex items-center hover:text-gray-300">
                  <FaRegFolder className="mr-2" />
                  Program
                </Link>
                <Link href="/FAQ" className="flex items-center hover:text-gray-300">
                  <FaQuestionCircle className="mr-2" />
                  FAQ
                </Link>
                {/* <Link href="/scholarships" className="flex items-center hover:text-gray-300">
                  <FaUniversity className="mr-2" />
                  Scholarships & Financial Aid
                </Link> */}
                <Link href="/join" className="flex items-center hover:text-gray-300">
                  <FaUserPlus className="mr-2" />
                  Join
                </Link>
                <Link href="/contact" className="flex items-center hover:text-gray-300">
                  <FaPhone className="mr-2" />
                  Contact
                </Link>
              </div>
            </div>
          )}

          {/* תוכן הדף */}
          <main className="container mx-auto flex-1 p-6">
            {children}
          </main>

          {/* כותרת תחתונה */}
          <footer className="bg-blue-600 text-white py-4">
            <div className="container mx-auto text-center">
              © 2025 Ting Global Academy . All rights reserved.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
